#!/usr/bin/env python3
#
# See the README on this nerdy little experiment.
#
# From: Rick van Rein <rick@groengemak.nl>


import sys
import math

# Check parameters
#
if len (sys.argv) != 4:
	sys.stderr.write ('Usage: %s SYS DIA BPM\n' % sys.argv [0])
	sys.exit (1)

# Harvest input
#
(moi,sys,dia,bpm) = sys.argv
sys = float (sys)
dia = float (dia)
bpm = float (bpm)


# How many halvations does your blood pressure make per minute?
#
hpm = math.log2 (sys/dia) * bpm

# What is your average blood pressure?
#
avg = math.sqrt (sys * dia)

# Print results
#
print ()
print ('Systolic /maximum pressure:           %4d' % int (round (sys, 0)))
print ('Diastolic/minimum pressure:           %4d' % int (round (dia, 0)))
print ('Heart beats per minute:               %4d' % int (round (bpm, 0)))
print ()
print ('Average blood pressure:               %4d' % int (round (avg, 0)))
print ('Blood pressure halvations per minute: %4d' % int (round (hpm, 0)))
print ()
